###############################################################################
#                                                                             #
# Copyright (C) 2019 Troels Schwarz-Linnet                                    #
# Copyright (C) 2019 Edward d'Auvergne                                        #
#                                                                             #
# This file is part of the program relax (http://www.nmr-relax.com).          #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

language: python
os: linux

addons:
  apt:
    packages:
        - openmpi-bin
        - libopenmpi-dev
        - ssh

env:
  global:
    - MPIRUN=""
    - OLD_PY2_PACKAGES=false
    - PYTHON=""
    - RELAX_ARGS=""
    - UPGRADE=false
    - WXPYTHON=false

jobs:
  include:
    # Linux (Ubuntu Xenial 16.04), Python 2.7, single processor.
    #   https://docs.travis-ci.com/user/reference/trusty/
    - name: "Linux (Ubuntu 16.04), Python 2.7, single processor, all tests."
      python: 2.7
      language: python
      dist: xenial
      services:
        - xvfb
      env: WXPYTHON=true OLD_PY2_PACKAGES=true
      before_install:
        # Conda is used to install wxPython 3.0.
        - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        #- conda update -q conda
        - conda info -a

    # Linux (Ubuntu Trusty 14.04), Python 3.6, multi processor (2 MPI processors).
    # Python 3.6 is standard version on Redhat 7 and Ubuntu LTS 18.04 and TS 16.04
    - name: "Linux (Ubuntu 14.04), Python 3.6, MPI multi processor, no GUI tests."
      python: 3.6
      language: python
      dist: trusty
      env: MPIRUN="mpirun -np 2" RELAX_ARGS="--multi='mpi4py'"

    # Linux (Ubuntu Xenial 16.04), Python 3.7.
    #   https://docs.travis-ci.com/user/reference/xenial
    #   https://github.com/travis-ci/travis-ci/issues/9815
    - name: "Linux (Ubuntu 16.04), Python 3.7, single processor, no GUI tests."
      python: 3.7
      language: python
      dist: xenial

    # Linux (Ubuntu Xenial 16.04), Python 3.7.
    # Try upgrade all pip packages.
    - name: "Linux (Ubuntu 16.04), Python 3.7, single processor, no GUI tests, upgraded pip packages."
      python: 3.7
      language: python
      dist: xenial
      env: UPGRADE=true

    # Mac OS X (10.13), Python 3.7.
    - name: "Mac OS X (10.13), Python 3.7, single processor, no GUI tests."
      os: osx
      language: shell
      python: 3.7
      before_install:
        - python3 -m pip install virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate

        # Fix for the Mac OS image rendering back end of matplotlib.
        - mkdir -p $HOME/.matplotlib/
        - "echo 'backend: TkAgg' > $HOME/.matplotlib/matplotlibrc"

    # MS Windows (10), Python 3.7.
    - name: "MS Windows (10), Python 3.7, single processor, no GUI tests."
      os: windows
      language: shell
      python: "3.7"
      before_install:
        - choco install python3 --version 3.7.4
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip

    # Arm64 Linux (Ubuntu Bionic 18.04), Python 3.6 (system).
    - name: "Arm64 Linux (Ubuntu 18.04), Python 3.6 (system), single processor, no GUI tests."
      python: 3.6
      language: python
      arch: arm64
      dist: bionic
      env:
        - PYTHON="/usr/bin/python3"
      before_install:
        - sudo apt-get -y install python3-pip
        - sudo apt-get -y install python3-numpy
        - sudo apt-get -y install python3-matplotlib
        - sudo apt-get -y install python3-scipy
        - sudo apt-get -y install python3-mpi4py
        - sudo apt-get -y install python3-wxgtk4.0
        - sudo apt-get -y install scons
      install:
        - /usr/bin/python --version
        - /usr/bin/python3 --version
        - /usr/bin/pip3 --version
        - /usr/bin/pip3 install -r devel_scripts/travis-ci/requirements.txt
        - /usr/bin/python3 /usr/bin/scons

    # API documentation build, Linux (Ubuntu Trusty 14.04), Python 2.7.
    - name: "API documentation build"
      python: 2.7
      language: python
      dist: trusty
      env: WXPYTHON=true OLD_PY2_PACKAGES=true
      before_install:
        # Conda is used to install wxPython 3.0.
        - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda info -a

        # Install the required epydoc Python module.
        - pip install epydoc
      script:
        - scons api_manual_html

    # FSF copyright validation, Linux (Ubuntu Xenial 16.04), Python 3.7.
    - name: "FSF copyright validation"
      python: 3.7
      language: python
      dist: xenial
      install:
        - set -e
      script:
        - git fetch --unshallow
        - ./devel_scripts/fsfcv -v -c ./devel_scripts/fsfcv.conf.py

install:
    # Fail on first error.
    - set -e

    # Find Python.h to build with scons.
    - export PYTHON_INCLUDE_DIR=`python -c 'from distutils import sysconfig; print(sysconfig.get_python_inc())'`

    # Debugging printout of environmental variables.
    - echo "MPIRUN=$MPIRUN ; OS=$TRAVIS_OS_NAME ; PIPUPGRADE=$UPGRADE ; VIRTUAL_ENV=$VIRTUAL_ENV ; PYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR"

    # Get newer pip and whell for binary caching support.
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo -H pip install --upgrade pip wheel; fi
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sudo -H pip install --upgrade pip wheel; fi

    # Manually install packages for Python 2.7 compatibility.
    - if [[ $OLD_PY2_PACKAGES == "true" ]]; then pip install numpy==1.16.5; else pip install numpy; fi
    - if [[ $OLD_PY2_PACKAGES == "true" ]]; then pip install matplotlib==2.2.4; else pip install matplotlib; fi
    - if [[ $OLD_PY2_PACKAGES == "true" ]]; then pip install scipy==1.2.2; else pip install scipy; fi

    # Install Python packages with pip.
    - if [[ $UPGRADE == "false" ]]; then pip install -r devel_scripts/travis-ci/requirements.txt; fi
    - if [[ $UPGRADE == "true" ]]; then pip install -U -r devel_scripts/travis-ci/requirements.txt; fi

    # Install Python package with pip for running with multiple processors.
    - if [[ $MPIRUN != "" ]]; then pip install mpi4py; fi

    # Install wxPython 3.0 using Conda.
    - if [[ $WXPYTHON == "true" ]]; then conda install -c https://conda.anaconda.org/travis wxpython; fi

    # Compile the C modules.
    - scons

script:
    # Fail on first error.
    - set -e

    # relax information printout.
    - $MPIRUN $PYTHON ./relax $RELAX_ARGS -i

    # Test suite execution.
    - if [[ $WXPYTHON == "true"  ]]; then $MPIRUN $PYTHON ./relax $RELAX_ARGS --time --test-suite; fi
    - if [[ $WXPYTHON == "false" ]]; then $MPIRUN $PYTHON ./relax $RELAX_ARGS --time --system-tests; fi
    - if [[ $WXPYTHON == "false" ]]; then $MPIRUN $PYTHON ./relax $RELAX_ARGS --time --unit-tests; fi
    - if [[ $WXPYTHON == "false" ]]; then $MPIRUN $PYTHON ./relax $RELAX_ARGS --time --verification-tests; fi

cache: pip
git:
  depth: 10

notifications:
  # https://docs.travis-ci.com/user/notifications/#configuring-email-notifications
  # Pull Request builds do not trigger email notifications.
  email:
    recipients:
      - nmr-relax-devel@lists.sourceforge.net
    on_success: change # default: change (always, never, change)
    on_failure: always # default: always
